from .clients import ClientViewSet
from .memberships import MembershipViewSet
from .payments import  PaymentViewSet
from .gyms import GymViewSet
from .products import ProductViewSet
from .inventories import InventoryViewSet
from .services import ServiceViewSet
from .plans import PlanViewSet
from .users import UserViewSet
from .payment_methods import PaymentMethodViewSet
from .sale import SaleViewSet
from .gymClass import GymClassViewSet
from .attendances import AttendanceWebhookView
