# Generated by Django 6.0.1 on 2026-02-03 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_client_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='financial_status',
            field=models.CharField(choices=[('PAID', 'Pagado'), ('DUE', 'Con Deuda')], default='DUE', max_length=20),
        ),
    ]
