# Generated by Django 6.0.1 on 2026-02-04 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_payment_options_alter_paymentmethod_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='financial_status',
            field=models.CharField(choices=[('Deuda', 'Deuda'), ('Parcial', 'Parcial'), ('Pagado', 'Pagado')], default='Deuda', max_length=20),
        ),
    ]
