# Generated by Django 6.0.1 on 2026-02-04 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_membership_notes_alter_membership_financial_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='clients/'),
        ),
    ]
