# Generated by Django 6.0.1 on 2026-02-04 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_client_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='upgrade_credit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
