# Generated by Django 6.0.1 on 2026-02-04 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_payment_created_by_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='payment_due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha límite de pago'),
        ),
    ]
