# Generated by Django 6.0.1 on 2026-02-04 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_membership_payment_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='is_synced_with_hik',
            field=models.BooleanField(default=False, help_text='Indica si la fecha de vencimiento se envió correctamente a la lectora.', verbose_name='Sincronizado con Hikvision'),
        ),
    ]
