# Generated by Django 6.0.1 on 2026-02-05 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_membership_is_synced_with_hik'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='sessions_consumed',
            field=models.IntegerField(default=0, verbose_name='Sesiones Consumidas'),
        ),
        migrations.AddField(
            model_name='membership',
            name='sessions_total',
            field=models.IntegerField(default=0, verbose_name='Sesiones Totales'),
        ),
    ]
