# Generated by Django 6.0.1 on 2026-02-05 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_membership_sessions_consumed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='birthday_message',
            field=models.CharField(default='¡Feliz cumpleaños {name}! 🎉 Pasa por el bar por tu regalo.', help_text='Usa {name} para insertar el nombre del socio automáticamente.', max_length=255),
        ),
        migrations.AddField(
            model_name='gym',
            name='expiration_alert_message',
            field=models.CharField(default='¡Hola {name}! Te quedan {days} días activos. ¡No olvides renovar!', help_text='Usa {name} para el nombre y {days} para los días restantes.', max_length=255),
        ),
    ]
