# Generated by Django 6.0.1 on 2026-02-05 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_gym_birthday_message_gym_expiration_alert_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-check_in_time']},
        ),
        migrations.AddField(
            model_name='attendance',
            name='membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.membership'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='message_displayed',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='check_in_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='core.client'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='gym',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='core.gym'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='method',
            field=models.CharField(choices=[('FINGERPRINT', 'Huella Digital'), ('QR', 'Código QR'), ('MANUAL', 'Manual/Secretaria')], default='FINGERPRINT', max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento'),
        ),
    ]
