# Generated by Django 6.0.1 on 2026-02-06 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_attendance_options_attendance_membership_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='courtesy_qty',
            field=models.PositiveIntegerField(default=0, verbose_name='Pases de cortesía'),
        ),
        migrations.AddField(
            model_name='membership',
            name='courtesy_used',
            field=models.PositiveIntegerField(default=0, verbose_name='Pases usados'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='operational_status',
            field=models.CharField(choices=[('ACTIVE', 'Activa'), ('SCHEDULED', 'Programada'), ('EXPIRED', 'Vencida'), ('CANCELLED', 'Cancelada'), ('INACTIVE', 'Inactiva'), ('FROZEN', 'Congelada')], default='SCHEDULED', max_length=20),
        ),
        # migrations.AddConstraint(
        #     model_name='membership',
        #     constraint=models.UniqueConstraint(condition=models.Q(('operational_status', 'ACTIVE')), fields=('client', 'gym'), name='uniq_active_membership_per_client_gym'),
        # ),
    ]
