# Generated by Django 6.0.1 on 2026-02-06 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_add_active_membership_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
