# Generated by Django 6.0.1 on 2026-02-06 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_membership_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='action',
            field=models.CharField(choices=[('INSCRIPTION', 'Inscripción'), ('RENEWAL', 'Renovación'), ('UPGRADE', 'Upgrade')], default='INSCRIPTION', max_length=20, verbose_name='Tipo de operación'),
        ),
    ]
