# Generated by Django 6.0.1 on 2026-02-06 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_membership_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='id_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='N.de identificacion'),
        ),
    ]
