# Generated by Django 6.0.1 on 2026-02-10 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_client_id_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='hikvision_id',
            field=models.CharField(blank=True, help_text='ID del usuario en la lectora Hikvision (employeeNoString)', max_length=32, null=True, unique=True),
        ),
    ]
