# Generated by Django 6.0.1 on 2026-02-11 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_client_hikvision_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='default_payment_grace_days',
            field=models.PositiveIntegerField(default=7, verbose_name='Días de gracia para pagos parciales'),
        ),
    ]
