# Generated by Django 6.0.2 on 2026-02-12 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_gym_default_payment_grace_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='enrollment_fee',
        ),
    ]
