# Generated by Django 6.0.2 on 2026-02-18 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_user_options_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RemoveConstraint(
            model_name='user',
            name='unique_email_when_not_null',
        ),
    ]
