# Generated by Django 6.0.2 on 2026-02-18 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_client_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveConstraint(
            model_name='client',
            name='unique_phone_per_gym',
        ),
        migrations.AlterField(
            model_name='client',
            name='first_name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='hikvision_id',
            field=models.CharField(blank=True, db_index=True, help_text='ID del usuario en la lectora Hikvision (employeeNoString)', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='id_number',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='N. de identificación'),
        ),
        migrations.AlterField(
            model_name='client',
            name='last_name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['gym', 'last_name'], name='core_client_gym_id_736b0a_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['gym', 'id_number'], name='core_client_gym_id_a1641e_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['gym', 'hikvision_id'], name='core_client_gym_id_d93c45_idx'),
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.UniqueConstraint(condition=models.Q(('phone__isnull', False)), fields=('phone', 'gym'), name='unique_phone_per_gym'),
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.UniqueConstraint(condition=models.Q(('id_number__isnull', False)), fields=('id_number', 'gym'), name='unique_id_number_per_gym'),
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.UniqueConstraint(condition=models.Q(('hikvision_id__isnull', False)), fields=('hikvision_id', 'gym'), name='unique_hikvision_per_gym'),
        ),
    ]
