# Generated by Django 6.0.2 on 2026-02-18 17:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_client_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='paymentmethod',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='gym',
            name='access_control_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='gym',
            name='auto_block_on_debt',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='gym',
            name='currency',
            field=models.CharField(default='USD', max_length=10),
        ),
        migrations.AddField(
            model_name='gym',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='gym',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='gym',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='gym_logos/'),
        ),
        migrations.AddField(
            model_name='gym',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='gym',
            name='primary_color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='gym',
            name='secondary_color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='provider',
            field=models.CharField(blank=True, help_text='Proveedor usado (Twilio, SMTP, Meta API, etc.)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gym',
            name='birthday_message',
            field=models.CharField(default='¡Feliz cumpleaños {name}! 🎉 Pasa por el bar por tu regalo.', max_length=255),
        ),
        migrations.AlterField(
            model_name='gym',
            name='expiration_alert_message',
            field=models.CharField(default='¡Hola {name}! Te quedan {days} días activos. ¡No olvides renovar!', max_length=255),
        ),
        migrations.AlterField(
            model_name='membership',
            name='courtesy_qty',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='membership',
            name='courtesy_used',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='membership',
            name='is_synced_with_hik',
            field=models.BooleanField(default=False, help_text='Indica si la fecha de vencimiento se envió correctamente a la lectora.'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='payment_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='sessions_consumed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='membership',
            name='sessions_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='notification',
            name='channel',
            field=models.CharField(choices=[('WHATSAPP', 'WhatsApp'), ('EMAIL', 'Email'), ('SMS', 'SMS'), ('APP', 'Push App')], max_length=15),
        ),
        migrations.AlterField(
            model_name='notification',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='core.client'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='gym',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.gym'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('SENT', 'Enviado'), ('FAILED', 'Fallido'), ('RETRY', 'Reintento')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.notificationtemplate'),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='body',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='type',
            field=models.CharField(choices=[('WELCOME', 'Bienvenida'), ('PAYMENT_REMINDER', 'Recordatorio de Pago'), ('MEMBERSHIP_EXPIRED', 'Membresía Vencida'), ('PROMOTION', 'Promoción'), ('ALERT', 'Alerta')], max_length=30),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('PAID', 'Pagado'), ('VOID', 'Anulado')], default='PAID', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='gym',
            field=models.ForeignKey(blank=True, help_text='Si es null, es un método global del sistema.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='core.gym'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='name',
            field=models.CharField(help_text='Ej: Efectivo, Transferencia, Tarjeta', max_length=100),
        ),
        migrations.AlterField(
            model_name='plan',
            name='code',
            field=models.CharField(blank=True, help_text='Código interno único por gimnasio.', max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='gym',
            index=models.Index(fields=['company'], name='core_gym_company_0c5f09_idx'),
        ),
        migrations.AddIndex(
            model_name='gym',
            index=models.Index(fields=['is_active'], name='core_gym_is_acti_4cec4d_idx'),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['gym', 'client'], name='core_member_gym_id_eff59b_idx'),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['operational_status'], name='core_member_operati_25d33e_idx'),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['financial_status'], name='core_member_financi_8a9ccb_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['gym'], name='core_notifi_gym_id_f05be2_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['status'], name='core_notifi_status_7f445c_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['channel'], name='core_notifi_channel_1a0224_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationtemplate',
            index=models.Index(fields=['type'], name='core_notifi_type_295c9c_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationtemplate',
            index=models.Index(fields=['is_active'], name='core_notifi_is_acti_38ce27_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['gym'], name='core_paymen_gym_id_29efd5_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['membership'], name='core_paymen_members_9c5f22_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_date'], name='core_paymen_payment_a103cb_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentmethod',
            index=models.Index(fields=['gym'], name='core_paymen_gym_id_bab5bd_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentmethod',
            index=models.Index(fields=['active'], name='core_paymen_active_64bf7e_idx'),
        ),
        migrations.AddIndex(
            model_name='plan',
            index=models.Index(fields=['gym'], name='core_plan_gym_id_df7a86_idx'),
        ),
        migrations.AddIndex(
            model_name='plan',
            index=models.Index(fields=['is_active'], name='core_plan_is_acti_173101_idx'),
        ),
        migrations.AddConstraint(
            model_name='gym',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='unique_gym_name_per_company'),
        ),
        migrations.AddConstraint(
            model_name='paymentmethod',
            constraint=models.UniqueConstraint(fields=('gym', 'name'), name='unique_payment_method_per_gym'),
        ),
        migrations.AddConstraint(
            model_name='plan',
            constraint=models.UniqueConstraint(fields=('gym', 'code'), name='unique_plan_code_per_gym'),
        ),
    ]
