# Generated by Django 6.0.2 on 2026-02-18 17:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='access_status',
            field=models.CharField(choices=[('GRANTED', 'Acceso Permitido'), ('DENIED', 'Acceso Denegado')], default='GRANTED', max_length=10),
        ),
        migrations.AddField(
            model_name='attendance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendance',
            name='device_id',
            field=models.CharField(blank=True, help_text='ID del dispositivo (lector, tablet, torniquete, etc.)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='source_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='method',
            field=models.CharField(choices=[('FINGERPRINT', 'Huella Digital'), ('QR', 'Código QR'), ('MANUAL', 'Manual/Secretaria'), ('FACE', 'Reconocimiento Facial'), ('CARD', 'Tarjeta RFID')], default='FINGERPRINT', max_length=20),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['gym'], name='core_attend_gym_id_626f63_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['client'], name='core_attend_client__e7300e_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['check_in_time'], name='core_attend_check_i_3379bf_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['access_status'], name='core_attend_access__f7936f_idx'),
        ),
    ]
