# Generated by Django 6.0.2 on 2026-02-18 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_attendance_access_status_attendance_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='attendance',
            name='core_attend_access__f7936f_idx',
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['gym', 'check_in_time'], name='core_attend_gym_id_4c0b25_idx'),
        ),
    ]
