# Generated by Django 6.0.2 on 2026-02-18 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0030_remove_attendance_core_attend_access__f7936f_idx_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_gym_admin',
        ),
        migrations.AlterField(
            model_name='user',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='core.company'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('STAFF', 'Staff'), ('CLIENT', 'Cliente')], default='CLIENT', max_length=10),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['company'], name='core_user_company_1ff1de_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['gym'], name='core_user_gym_id_787fb6_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='core_user_role_73872d_idx'),
        ),
    ]
