# Generated by Django 6.0.2 on 2026-02-20 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_delete_role_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
