# Generated by Django 6.0.2 on 2026-02-20 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_client_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='courtesy_pass_balance',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='client',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals_made', to='core.client'),
        ),
        migrations.AddField(
            model_name='client',
            name='total_referrals',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
