# Generated by Django 6.0.2 on 2026-02-20 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_client_courtesy_pass_balance_client_referred_by_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='client',
            name='unique_phone_per_gym',
        ),
        migrations.RemoveConstraint(
            model_name='client',
            name='unique_id_number_per_gym',
        ),
        migrations.RemoveConstraint(
            model_name='client',
            name='unique_hikvision_per_gym',
        ),
        migrations.RemoveIndex(
            model_name='client',
            name='core_client_gym_id_736b0a_idx',
        ),
        migrations.RemoveIndex(
            model_name='client',
            name='core_client_gym_id_a1641e_idx',
        ),
        migrations.RemoveIndex(
            model_name='client',
            name='core_client_gym_id_d93c45_idx',
        ),
        migrations.AddField(
            model_name='client',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='core.company'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='client',
            name='gym',
        ),
    ]
