# Generated by Django 6.0.2 on 2026-02-20 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_remove_client_unique_phone_per_gym_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientGym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gym_links', to='core.client')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_links', to='core.gym')),
            ],
            options={
                'unique_together': {('client', 'gym')},
            },
        ),
    ]
