# Generated by Django 6.0.2 on 2026-02-20 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_clientgym'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='country',
            field=models.CharField(db_index=True, default='EC', help_text='Código ISO-2 del país (EC, CO, VE, etc.)', max_length=2),
        ),
        migrations.AddField(
            model_name='client',
            name='document_type',
            field=models.CharField(choices=[('NATIONAL_ID', 'Documento Nacional'), ('PASSPORT', 'Pasaporte')], db_index=True, default='NATIONAL_ID', max_length=20),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['company', 'country', 'document_type', 'id_number'], name='core_client_company_cd19c0_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['company', 'is_active'], name='core_client_company_e67d36_idx'),
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.UniqueConstraint(condition=models.Q(('id_number__isnull', False)), fields=('company', 'country', 'document_type', 'id_number'), name='unique_document_per_company'),
        ),
    ]
