# Generated by Django 6.0.2 on 2026-02-21 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_client_country_client_document_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='plan_type',
            field=models.CharField(choices=[('TIME', 'Por Tiempo'), ('SESSIONS', 'Por Sesiones')], default='TIME', max_length=20),
        ),
    ]
