# Generated by Django 6.0.2 on 2026-02-21 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_alter_plan_plan_type'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='membership',
            name='uniq_active_membership_per_client_gym',
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(condition=models.Q(('operational_status', 'ACTIVE')), fields=('client', 'gym', 'plan'), name='uniq_active_membership_per_client_gym_plan'),
        ),
    ]
