# Generated by Django 6.0.2 on 2026-02-21 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_remove_membership_uniq_active_membership_per_client_gym_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='is_allowed',
            field=models.BooleanField(default=True),
        ),
    ]
