# Generated by Django 6.0.2 on 2026-02-23 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_attendance_is_allowed'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='freeze_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='total_freeze_days',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
