# Generated by Django 6.0.2 on 2026-02-24 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_membership_freeze_requested_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='gym',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='core.gym'),
            preserve_default=False,
        ),
    ]
