# Generated by Django 6.0.2 on 2026-02-26 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_payment_balance_after_payment_balance_before'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='payment_grace_days_override',
            field=models.PositiveIntegerField(blank=True, help_text='Override de días de gracia para esta membresía. Si es null, usa el valor del gym.', null=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='sale_type',
            field=models.CharField(choices=[('CASH', 'Contado'), ('CREDIT', 'Crédito')], default='CASH', max_length=10),
        ),
    ]
