# Generated by Django 6.0.2 on 2026-02-27 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_user_must_change_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='support_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
