# Generated by Django 6.0.2 on 2026-02-27 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_company_support_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('EMAIL', 'Email'), ('PHONE', 'Phone')], db_index=True, max_length=10)),
                ('value', models.CharField(db_index=True, max_length=255)),
                ('is_primary', models.BooleanField(db_index=True, default=False)),
                ('is_verified', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(blank=True, help_text='Cliente asociado (si existe).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_points', to='core.client')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_points', to='core.company')),
                ('user', models.ForeignKey(blank=True, help_text='Cuenta asociada (si existe).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_points', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['company', 'type', 'value'], name='core_contac_company_69db59_idx'), models.Index(fields=['company', 'client', 'type'], name='core_contac_company_b7b405_idx'), models.Index(fields=['company', 'user', 'type'], name='core_contac_company_beb60f_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'type', 'value'), name='uniq_contactpoint_company_type_value')],
            },
        ),
    ]
