# Generated by Django 6.0.2 on 2026-03-05 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_emailverificationtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='renovation_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
