# Generated by Django 6.0.2 on 2026-03-08 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_membership_renovation_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='payment_grace_days_override',
        ),
        migrations.AlterField(
            model_name='membership',
            name='financial_status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('PARTIAL', 'Parcial'), ('PAID', 'Pagado')], default='PENDING', max_length=20),
        ),
    ]
