# Generated by Django 6.0.2 on 2026-03-12 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_remove_membership_payment_grace_days_override_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HikvisionAccessEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_event_id', models.CharField(blank=True, db_index=True, help_text='ID único del evento en Hikvision o en el gateway, si existe.', max_length=150, null=True)),
                ('event_fingerprint', models.CharField(help_text='Hash o fingerprint único para evitar duplicados.', max_length=255, unique=True)),
                ('hikvision_person_id', models.CharField(blank=True, db_index=True, help_text='Person ID / employeeNo / identificador recibido desde Hikvision.', max_length=100, null=True)),
                ('device_id', models.CharField(blank=True, db_index=True, help_text='ID o serial del dispositivo que originó el evento.', max_length=100, null=True)),
                ('device_name', models.CharField(blank=True, help_text='Nombre descriptivo del dispositivo.', max_length=150, null=True)),
                ('direction', models.CharField(choices=[('ENTRY', 'Entrada'), ('EXIT', 'Salida'), ('UNKNOWN', 'Desconocida')], db_index=True, default='UNKNOWN', max_length=10)),
                ('method', models.CharField(blank=True, default='', help_text='Método detectado: FACE, FINGERPRINT, CARD, QR, etc.', max_length=20)),
                ('access_result', models.CharField(blank=True, default='', help_text='Resultado técnico del evento: granted, denied, unknown, etc.', max_length=20)),
                ('occurred_at', models.DateTimeField(blank=True, db_index=True, help_text='Momento real en que ocurrió el evento en el dispositivo.', null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Momento en que el backend recibió el evento.')),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('processing_status', models.CharField(choices=[('PENDING', 'Pendiente'), ('PROCESSED', 'Procesado'), ('IGNORED', 'Ignorado'), ('FAILED', 'Fallido')], db_index=True, default='PENDING', max_length=20)),
                ('processing_error', models.TextField(blank=True, default='')),
                ('raw_payload', models.JSONField(blank=True, default=dict, help_text='Payload original recibido desde Hikvision o gateway.')),
                ('notes', models.TextField(blank=True, default='')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hikvision_access_events', to='core.client')),
                ('gym', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hikvision_access_events', to='core.gym')),
                ('membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hikvision_access_events', to='core.membership')),
            ],
            options={
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['gym', 'received_at'], name='core_hikvis_gym_id_1cf434_idx'), models.Index(fields=['client', 'received_at'], name='core_hikvis_client__77ef6b_idx'), models.Index(fields=['hikvision_person_id'], name='core_hikvis_hikvisi_3fbb91_idx'), models.Index(fields=['device_id', 'received_at'], name='core_hikvis_device__159c04_idx'), models.Index(fields=['direction', 'received_at'], name='core_hikvis_directi_afaab5_idx'), models.Index(fields=['processing_status', 'received_at'], name='core_hikvis_process_e88903_idx')],
            },
        ),
    ]
