# Generated by Django 6.0.2 on 2026-03-12 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_alter_hikvisionaccessevent_access_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='tv_event_display_seconds',
            field=models.PositiveIntegerField(default=10, help_text='Segundos que se muestra el evento antes de volver al modo idle.'),
        ),
        migrations.AddField(
            model_name='gym',
            name='tv_idle_image_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='gym',
            name='tv_idle_message',
            field=models.CharField(blank=True, default='Esperando próximo acceso...', max_length=255),
        ),
        migrations.AddField(
            model_name='gym',
            name='tv_idle_mode',
            field=models.CharField(default='text', help_text='Modo idle de la TV: text, image, video, youtube', max_length=20),
        ),
        migrations.AddField(
            model_name='gym',
            name='tv_idle_subtitle',
            field=models.CharField(blank=True, default='¡Transforma tu vida!', max_length=150),
        ),
        migrations.AddField(
            model_name='gym',
            name='tv_idle_title',
            field=models.CharField(blank=True, default='Dorians Gym', max_length=150),
        ),
        migrations.AddField(
            model_name='gym',
            name='tv_idle_video_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='gym',
            name='tv_idle_youtube_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
